/** @type {import('tailwindcss').Config} */
import formsPlugin from '@tailwindcss/forms';
import containerQueriesPlugin from '@tailwindcss/container-queries';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: ["class", "class"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#a98fff",
        "surface-container-high": "#141f38",
        "on-tertiary-fixed-variant": "#70103b",
        "tertiary": "#ff97b8",
        "background": "#060e20",
        "on-error": "#490013",
        "tertiary-fixed-dim": "#f57ca5",
        "on-surface-variant": "#a3aac4",
        "secondary-fixed": "#d5e3fc",
        "on-primary-fixed": "#000000",
        "on-error-container": "#ffb2b9",
        "tertiary-fixed": "#ff8db2",
        "on-secondary-fixed-variant": "#4e5c71",
        "inverse-on-surface": "#4d556b",
        "surface-container-highest": "#192540",
        "surface-tint": "#b6a0ff",
        "on-secondary-container": "#c3d1e9",
        "primary-container": "#a98fff",
        "surface-container": "#0f1930",
        "secondary-container": "#3a485b",
        "on-secondary": "#455367",
        "surface": "#060e20",
        "on-secondary-fixed": "#324053",
        "inverse-primary": "#6834eb",
        "primary": "#b6a0ff",
        "error-container": "#a70138",
        "on-primary-fixed-variant": "#32008a",
        "outline": "#6d758c",
        "secondary-dim": "#c7d5ed",
        "surface-container-low": "#091328",
        "primary-fixed-dim": "#9c7eff",
        "secondary-fixed-dim": "#c7d5ed",
        "surface-variant": "#192540",
        "outline-variant": "#40485d",
        "on-tertiary": "#6a0936",
        "on-tertiary-container": "#59002b",
        "error-dim": "#d73357",
        "surface-bright": "#1f2b49",
        "on-tertiary-fixed": "#380019",
        "on-background": "#dee5ff",
        "on-surface": "#dee5ff",
        "surface-dim": "#060e20",
        "inverse-surface": "#faf8ff",
        "tertiary-container": "#fc81ab",
        "on-primary-container": "#280072",
        "on-primary": "#340090",
        "tertiary-dim": "#ef77a0",
        "error": "#ff6e84",
        "primary-dim": "#7e51ff",
        "surface-container-lowest": "#000000",
        "secondary": "#d5e3fc",
        "border": "var(--border)",
        "input": "var(--input)",
        "ring": "var(--ring)",
        "foreground": "var(--foreground)",
        "background": "var(--background)",
        "muted": "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        "accent": "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        "popover": "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        "card": "var(--card)",
        "card-foreground": "var(--card-foreground)",
        "destructive": "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        "success": "var(--success)"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [formsPlugin, containerQueriesPlugin],
}
